version: '3.8'

services:
  mongo:
    image: mongo:5
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: ./back-end
    container_name: backend
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/devopsdb
    depends_on:
      - mongo
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./front-end
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000/api

volumes:
  mongo-data: